import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { SmoothCursor } from "@/components/ui/smooth-cursor"
import { ToastContainer   } from 'react-toastify';

const Josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html
      lang="en"
      className={` ${Josefin.className}  h-full antialiased scrollbar-none`}

    >
      <body className="  min-h-full flex flex-col">
        {/* <SmoothCursor /> */}
        <ToastContainer position="top-left" closeOnClick />
        {children}</body>
    </html>
  );
}
